# Generated by Django 2.2.6 on 2019-10-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
